["ZSN_Clearweapon",			"CHECKBOX",	["Clear Primary Weapon","Player starts with cleared primary weapon"],										["ZluskeN Utilities Settings","Gear Settings"],True,	nil,{params ["_value"]; ZSN_Clearweapon = _value;},true] call CBA_fnc_addSetting;
["ZSN_AutoRearm",			"CHECKBOX",	["Automatic Rearm","Player will automatically pick up compatible magazines for their primary weapon"],		["ZluskeN Utilities Settings","Gear Settings"],True,	nil,{params ["_value"]; ZSN_AutoRearm = _value;},false] call CBA_fnc_addSetting;
["ZSN_Blockmags",			"CHECKBOX",	["Hide Magazines for other sides","Disable picking up magazines belonging to different side"],				["ZluskeN Utilities Settings","Gear Settings"],True,	nil,{params ["_value"]; ZSN_Blockmags = _value;},false] call CBA_fnc_addSetting;
["ZSN_Tun_Respawn_OldGear",	"CHECKBOX",	["Respawn with old gear","Players will respawn without replenished gear (TUN Respawn)"],					["ZluskeN Utilities Settings","Gear Settings"],True,	nil,{params ["_value"]; ZSN_Tun_Respawn_OldGear = _value;},false] call CBA_fnc_addSetting;
["ZSN_MedicalItems",		"CHECKBOX",	["More Medical Items","Units get issued additional medical gear (ACE)"],									["ZluskeN Utilities Settings","Gear Settings"],True,	nil,{params ["_value"]; ZSN_MedicalItems = _value;},true] call CBA_fnc_addSetting;
["ZSN_Autoswitch",			"CHECKBOX",	["Auto switch to handgun","Switch to handgun automatically when primary weapon runs out of ammo in combat"],["ZluskeN Utilities Settings","Gear Settings"],True,	nil,{params ["_value"]; ZSN_AutoSwitch = _value;},false] call CBA_fnc_addSetting;
["ZSN_NerfMG",				"CHECKBOX",	["Force Machine Gunners to Fire Stationary","Players with belt fed weapons can not fire while moving"],		["ZluskeN Utilities Settings","Gear Settings"],True,	nil,{params ["_value"]; ZSN_NerfMG = _value;},false] call CBA_fnc_addSetting;

["ZSN_MedicFacility",		"CHECKBOX",	["Medics are Facilities","Medics get configured as medical facilities (ACE)"],								["ZluskeN Utilities Settings","Gameplay Settings"],False,		nil,{params ["_value"]; ZSN_MedicFacility = _value;},true] call CBA_fnc_addSetting;
["ZSN_GrenadeTrack",		"CHECKBOX",	["Allow Planting of Grenades in Tank Tracks","Hand Grenades can be used to detrack enemy tanks (ACE)"],		["ZluskeN Utilities Settings","Gameplay Settings"],True,		nil,{params ["_value"]; ZSN_GrenadeTrack = _value;},false] call CBA_fnc_addSetting;
["ZSN_Wildfire",			"CHECKBOX",	["Cookoffs Start Forest Fires","ACE Cookoff events can start forest fires (ACE Weather + Wildfire)"],		["ZluskeN Utilities Settings","Gameplay Settings"],False,		nil,{params ["_value"]; ZSN_Wildfire = _value;},false] call CBA_fnc_addSetting;
["ZSN_AloneWarning",		"SLIDER",	["Warn Players When Isolated","Slider determines distance in meters before warning appears"],				["ZluskeN Utilities Settings","Gameplay Settings"],[0,500,0,0],	nil,{params ["_value"]; ZSN_AloneWarning = _value;},false] call CBA_fnc_addSetting;
["ZSN_DisableTI",			"LIST",		["Allow Thermal Imagers","Allow Thermal Imagers and Night Vision on vehicles"],								["ZluskeN Utilities Settings","Gameplay Settings"],[["ON","NIGHT","OFF"],["Allowed","Only At Night","Not Allowed"], 1],nil,{params ["_value"]; ZSN_DisableTI = _value; [] spawn zsn_fnc_disableNVG},false] call CBA_fnc_addSetting;
["ZSN_ShowGPS",				"CHECKBOX",	["Show position on map","Players position will be shown on map if GPS is equipped"],						["ZluskeN Utilities Settings","Gameplay Settings"],True,	nil,{params ["_value"]; ZSN_ShowGPS = _value;},false] call CBA_fnc_addSetting;
["ZSN_RemoveMaps",			"CHECKBOX",	["Remove ItemMap","Remove maps for non-squad leaders with Private rank"],									["ZluskeN Utilities Settings","Gameplay Settings"],False,	nil,{params ["_value"]; ZSN_RemoveMaps = _value;},true] call CBA_fnc_addSetting;
["ZSN_Deadmarkers",			"CHECKBOX",	["Create Markers On Dead Units","Places a marker on all killed units"],										["ZluskeN Utilities Settings","Gameplay Settings"],False,	nil,{params ["_value"]; ZSN_Deadmarkers = _value;},false] call CBA_fnc_addSetting;

["ZSN_Armorshake",			"CHECKBOX",	["Camerashake when tracked armor is close","Scales with weight, numbers and distance"],						["ZluskeN Utilities Settings","Misc. Settings"],True,		nil,{params ["_value"]; ZSN_Armorshake = _value;},false] call CBA_fnc_addSetting;
["ZSN_Jukebox",				"CHECKBOX",	["Jukebox","Dynamic ambient Music"],																		["ZluskeN Utilities Settings","Misc. Settings"],False,		nil,{params ["_value"]; ZSN_Jukebox = _value; if (ZSN_Jukebox) then {["initialize"] call BIS_fnc_jukebox} else {if (["isInitialized"] call BIS_fnc_jukebox) then {["terminate"] call BIS_fnc_jukebox}}},false] call CBA_fnc_addSetting;

["ZSN_AllowRandomWeapon",	"CHECKBOX",	["Allow Random Weapon","Allow players to give themselves a random weapon"],									["ZluskeN Utilities Settings","Misc. Settings"],False,		nil,{params ["_value"]; ZSN_AllowRandomWeapon = _value;},false] call CBA_fnc_addSetting;
["ZSN_AllowArsenal",		"CHECKBOX",	["Allow Arsenal","Allow players to create faction Arsenal"],												["ZluskeN Utilities Settings","Misc. Settings"],False,		nil,{params ["_value"]; ZSN_AllowArsenal = _value;},false] call CBA_fnc_addSetting;

["ZSN_Unitpos",				"CHECKBOX",	["AI Default Unit Pos 'Stand up'","Set default unitposweak to 'UP' for AI"],								["ZluskeN Utilities Settings","Misc. Settings"],True,		nil,{params ["_value"]; ZSN_Unitpos = _value;},false] call CBA_fnc_addSetting;
["ZSN_CombatMode",			"LIST",	["Set AI Combat Mode","Set default combat mode for AI"],														["ZluskeN Utilities Settings","Misc. Settings"],[["","GREEN","WHITE","YELLOW","RED"],["Unchanged","Hold fire, keep formation","Hold fire, engage at will","Fire at will, keep formation","Fire at will, engage at will"], 0],nil,{params ["_value"]; ZSN_CombatMode = _value;},false] call CBA_fnc_addSetting;