["ZSN_Clearweapon",			"CHECKBOX",	["Clear Primary Weapon","Player starts with cleared primary weapon"],										["ZluskeN Utilities Settings","Gear Settings"],True,	nil,{params ["_value"]; ZSN_Clearweapon = _value;},true] call CBA_fnc_addSetting;
["ZSN_AutoRearm",			"CHECKBOX",	["Automatic Rearm","Player will automatically pick up compatible magazines for their primary weapon"],		["ZluskeN Utilities Settings","Gear Settings"],False,	nil,{params ["_value"]; ZSN_AutoRearm = _value;},false] call CBA_fnc_addSetting;
["ZSN_Blockmags",			"CHECKBOX",	["Hide Magazines for other sides","Disable picking up magazines belonging to different side"],				["ZluskeN Utilities Settings","Gear Settings"],False,	nil,{params ["_value"]; ZSN_Blockmags = _value;},false] call CBA_fnc_addSetting;
["ZSN_Tun_Respawn_OldGear",	"CHECKBOX",	["Respawn with old gear","Players will respawn without replenished gear (TUN Respawn)"],					["ZluskeN Utilities Settings","Gear Settings"],False,	nil,{params ["_value"]; ZSN_Tun_Respawn_OldGear = _value;},false] call CBA_fnc_addSetting;
["ZSN_MedicalItems",		"CHECKBOX",	["More Medical Items","Units get issued additional medical gear (ACE)"],									["ZluskeN Utilities Settings","Gear Settings"],False,	nil,{params ["_value"]; ZSN_MedicalItems = _value;},true] call CBA_fnc_addSetting;
["ZSN_NerfMG",				"CHECKBOX",	["Nerf Heavy Gunners","Players with heavy weapons can not ADS while moving and are forced to slow walk while firing"],["ZluskeN Utilities Settings","Gear Settings"],False,	nil,{params ["_value"]; ZSN_NerfMG = _value;},false] call CBA_fnc_addSetting;
["ZSN_Throwing",			"CHECKBOX",	["Allow Throwing Rocks and Magazines","Players can throw magazines and rocks at each other"],				["ZluskeN Utilities Settings","Gear Settings"],True,	nil,{params ["_value"]; ZSN_Throwing = _value;},false] call CBA_fnc_addSetting;

["ZSN_ShowGPS",				"CHECKBOX",	["Show position on map","Players position will be shown on map if GPS is equipped"],						["ZluskeN Utilities Settings","Gear Settings"],True,	nil,{params ["_value"]; ZSN_ShowGPS = _value;},false] call CBA_fnc_addSetting;
["ZSN_RemoveMaps",			"CHECKBOX",	["Remove ItemMap","Remove maps for non-squad leaders with Private rank"],									["ZluskeN Utilities Settings","Gear Settings"],False,	nil,{params ["_value"]; ZSN_RemoveMaps = _value;},true] call CBA_fnc_addSetting;

["ZSN_MedicFacility",		"CHECKBOX",	["Medics are Facilities","Medics get configured as medical facilities (ACE)"],								["ZluskeN Utilities Settings","Gameplay Settings"],True,	nil,{params ["_value"]; ZSN_MedicFacility = _value;},true] call CBA_fnc_addSetting;
["ZSN_Wildfire",			"CHECKBOX",	["Cookoffs Start Forest Fires","ACE Cookoff events can start forest fires (ACE Weather + Wildfire)"],		["ZluskeN Utilities Settings","Gameplay Settings"],False,	nil,{params ["_value"]; ZSN_Wildfire = _value;},false] call CBA_fnc_addSetting;
["ZSN_Deadmarkers",			"CHECKBOX",	["Create Markers On Dead Units","Places a marker on all killed units"],										["ZluskeN Utilities Settings","Gameplay Settings"],False,	nil,{params ["_value"]; ZSN_Deadmarkers = _value;},false] call CBA_fnc_addSetting;
["ZSN_Autoswitch",			"CHECKBOX",	["Auto switch to handgun","Switch to handgun automatically when primary weapon runs out of ammo in combat"],["ZluskeN Utilities Settings","Gameplay Settings"],True,	nil,{params ["_value"]; ZSN_AutoSwitch = _value;},false] call CBA_fnc_addSetting;
["ZSN_GrenadeTrack",		"CHECKBOX",	["Allow Planting of Grenades in Tank Tracks","Hand Grenades can be used to detrack enemy tanks (ACE)"],		["ZluskeN Utilities Settings","Gameplay Settings"],True,	nil,{params ["_value"]; ZSN_GrenadeTrack = _value;},false] call CBA_fnc_addSetting;
["ZSN_DisableTI",			"LIST",		["Allow Thermal Imagers","Allow Thermal Imagers and Night Vision on vehicles"],								["ZluskeN Utilities Settings","Gameplay Settings"],[["ON","NIGHT","OFF"],["Allowed","Only At Night","Not Allowed"], 1],nil,{params ["_value"]; ZSN_DisableTI = _value; [] spawn zsn_fnc_disableNVG},false] call CBA_fnc_addSetting;
["ZSN_Fuelmultiplier",		"SLIDER",	["Fuel Multiplier","Reduce the capacities of fueltanks to create a need for refueling more often"],			["ZluskeN Utilities Settings","Gameplay Settings"],[0.01,1,1,2,true],nil,{params ["_value"]; ZSN_Fuelmultiplier = _value;},false] call CBA_fnc_addSetting;
["ZSN_AloneWarning",		"SLIDER",	["Warn Players When Isolated","Slider determines distance in meters before warning appears"],				["ZluskeN Utilities Settings","Gameplay Settings"],[0,500,0,0],	nil,{params ["_value"]; ZSN_AloneWarning = _value;},false] call CBA_fnc_addSetting;

["ZSN_WestStacheChance",	"SLIDER",	["Moustache Probability (BLUFOR)","Percentage of BLUFOR units that will start with a Cold War Moustache"],	["ZluskeN Utilities Settings","Misc. Settings"],[0,1,0,2,true],nil,{params ["_value"]; ZSN_WestStacheChance = _value;},false] call CBA_fnc_addSetting;
["ZSN_EastStacheChance",	"SLIDER",	["Moustache Probability (OPFOR)","Percentage of OPFOR units that will start with a Cold War Moustache"],	["ZluskeN Utilities Settings","Misc. Settings"],[0,1,0,2,true],nil,{params ["_value"]; ZSN_EastStacheChance = _value;},false] call CBA_fnc_addSetting;
["ZSN_GuerStacheChance",	"SLIDER",	["Moustache Probability (INDEP)","Percentage of INDEP units that will start with a Cold War Moustache"],	["ZluskeN Utilities Settings","Misc. Settings"],[0,1,0,2,true],nil,{params ["_value"]; ZSN_GuerStacheChance = _value;},false] call CBA_fnc_addSetting;
["ZSN_CivStacheChance",		"SLIDER",	["Moustache Probability (CIV)","Percentage of Civilian units that will start with a Cold War Moustache"],	["ZluskeN Utilities Settings","Misc. Settings"],[0,1,0,2,true],nil,{params ["_value"]; ZSN_CivStacheChance = _value;},false] call CBA_fnc_addSetting;
["ZSN_Staches",				"EDITBOX",	["Moustache List","List of Moustache Classnames (Can be used to add different facewear)"],					["ZluskeN Utilities Settings","Misc. Settings"],"SP_Moustache,SP_Moustache_Blonde,SP_Moustache_Brown,SP_Moustache_Ginger,SP_Moustache_White",nil,{params ["_value"]; ZSN_Staches = _value splitString ",";},false] call CBA_fnc_addSetting;

//["ZSN_FemalePlayer",		"CHECKBOX",	["Player is Female","Make the Player Character Female (Max Women, TFTW, RHS)"],								["ZluskeN Utilities Settings","Misc. Settings"],False,	nil,{params ["_value"]; ZSN_FemalePlayer = _value;},false] call CBA_fnc_addSetting;
["ZSN_Armorshake",			"CHECKBOX",	["Camerashake when tracked armor is close","Scales with weight, numbers and distance"],						["ZluskeN Utilities Settings","Misc. Settings"],True,	nil,{params ["_value"]; ZSN_Armorshake = _value;},false] call CBA_fnc_addSetting;
["ZSN_Jukebox",				"CHECKBOX",	["Jukebox","Dynamic ambient Music"],																		["ZluskeN Utilities Settings","Misc. Settings"],False,	nil,{params ["_value"]; ZSN_Jukebox = _value; if (ZSN_Jukebox) then {["initialize"] call BIS_fnc_jukebox} else {if (["isInitialized"] call BIS_fnc_jukebox) then {["terminate"] call BIS_fnc_jukebox}}},false] call CBA_fnc_addSetting;
["ZSN_AllowRandomWeapon",	"CHECKBOX",	["Allow Random Weapon","Allow players to give themselves a random weapon"],									["ZluskeN Utilities Settings","Misc. Settings"],False,	nil,{params ["_value"]; ZSN_AllowRandomWeapon = _value;},false] call CBA_fnc_addSetting;
["ZSN_AllowArsenal",		"CHECKBOX",	["Allow Arsenal","Allow players to create faction Arsenal"],												["ZluskeN Utilities Settings","Misc. Settings"],False,	nil,{params ["_value"]; ZSN_AllowArsenal = _value;},false] call CBA_fnc_addSetting;
["ZSN_Unitpos",				"CHECKBOX",	["AI Default Unit Pos 'Stand up'","Set default unitposweak to 'UP' for AI"],								["ZluskeN Utilities Settings","Misc. Settings"],True,	nil,{params ["_value"]; ZSN_Unitpos = _value;},false] call CBA_fnc_addSetting;
["ZSN_CombatMode",			"LIST",		["Set AI Combat Mode","Set default combat mode for AI"],													["ZluskeN Utilities Settings","Misc. Settings"],[["","GREEN","WHITE","YELLOW","RED"],["Unchanged","Hold fire, keep formation","Hold fire, engage at will","Fire at will, keep formation","Fire at will, engage at will"], 0],nil,{params ["_value"]; ZSN_CombatMode = _value;},false] call CBA_fnc_addSetting;
