["ZSN_Clearweapon",			"CHECKBOX",	["Clear Primary Weapon","Player starts with cleared primary weapon"],										"ZluskeN Gunplay Settings",True,	nil,{params ["_value"]; ZSN_Clearweapon = _value;},true] call CBA_fnc_addSetting;
["ZSN_AutoRearm",			"CHECKBOX",	["Automatic Rearm","Player will automatically pick up compatible magazines for their primary weapon"],		"ZluskeN Gunplay Settings",False,	nil,{params ["_value"]; ZSN_AutoRearm = _value;},false] call CBA_fnc_addSetting;
["ZSN_Blockmags",			"CHECKBOX",	["Hide Magazines for other sides","Disable picking up magazines belonging to different side"],				"ZluskeN Gunplay Settings",False,	nil,{params ["_value"]; ZSN_Blockmags = _value;},false] call CBA_fnc_addSetting;
["ZSN_Tun_Respawn_OldGear",	"CHECKBOX",	["Respawn with old gear","Players will respawn without replenished gear (TUN Respawn)"],					"ZluskeN Gunplay Settings",False,	nil,{params ["_value"]; ZSN_Tun_Respawn_OldGear = _value;},false] call CBA_fnc_addSetting;
["ZSN_NerfMG",				"CHECKBOX",	["Nerf Heavy Gunners","Players with heavy weapons can not ADS while moving and are forced to slow walk while firing"],"ZluskeN Gunplay Settings",False,	nil,{params ["_value"]; ZSN_NerfMG = _value;},false] call CBA_fnc_addSetting;
["ZSN_Throwing",			"CHECKBOX",	["Allow Throwing Rocks and Magazines","Players can throw magazines and rocks at each other"],				"ZluskeN Gunplay Settings",True,	nil,{params ["_value"]; ZSN_Throwing = _value;},false] call CBA_fnc_addSetting;
["ZSN_Autoswitch",			"CHECKBOX",	["Auto switch to handgun","Switch to handgun automatically when primary weapon runs out of ammo in combat"],"ZluskeN Gunplay Settings",True,	nil,{params ["_value"]; ZSN_AutoSwitch = _value;},false] call CBA_fnc_addSetting;
["ZSN_GrenadeTrack",		"CHECKBOX",	["Allow Planting of Grenades in Tank Tracks","Hand Grenades can be used to detrack enemy tanks (ACE)"],		"ZluskeN Gunplay Settings",True,	nil,{params ["_value"]; ZSN_GrenadeTrack = _value;},false] call CBA_fnc_addSetting;
//["ZSN_AllowRandomWeapon",	"CHECKBOX",	["Allow Random Weapon","Allow players to give themselves a random weapon"],									"ZluskeN Gunplay Settings",False,	nil,{params ["_value"]; ZSN_AllowRandomWeapon = _value;},false] call CBA_fnc_addSetting;
["ZSN_AllowArsenal",		"CHECKBOX",	["Allow Arsenal","Allow players to create faction Arsenal"],												"ZluskeN Gunplay Settings",False,	nil,{params ["_value"]; ZSN_AllowArsenal = _value;},false] call CBA_fnc_addSetting;

ZSN_Grenades = [
	"HandGrenade",
	"MiniGrenade",
	"ACE_M14",
	"CUP_HandGrenade_L109A1_HE",
	"CUP_HandGrenade_L109A2_HE",
	"CUP_HandGrenade_M67",
	"CUP_HandGrenade_RGD5",
	"CUP_HandGrenade_RGO",
	"sfp_handgrenade_shgr07",
	"sfp_handgrenade_shgr2000",
	"sfp_handgrenade_shgr56",
	"gm_handgrenade_frag_dm41",
	"gm_handgrenade_frag_dm41a1",
	"gm_handgrenade_frag_dm51",
	"gm_handgrenade_frag_dm51a1",
	"gm_handgrenade_frag_m26",
	"gm_handgrenade_frag_m26a1",
	"gm_handgrenade_frag_rgd5",
	"vn_chicom_grenade_mag",
	"vn_f1_grenade_mag",
	"vn_m14_grenade_mag",
	"vn_m14_early_grenade_mag",
	"vn_m61_grenade_mag",
	"vn_m67_grenade_mag",
	"vn_rg42_grenade_mag",
	"vn_rgd33_grenade_mag",
	"vn_rgd5_grenade_mag",
	"vn_v40_grenade_mag",
	"vn_rkg3_grenade_mag",
	"vn_satchelcharge_02_throw_mag",
	"rhs_mag_rgd5",
	"rhs_grenade_m1939e_f_mag",
	"rhs_grenade_m1939l_f_mag",
	"rhs_mag_f1",
	"rhs_grenade_mkii_mag",
	"rhs_grenade_sthgr43_mag",
	"rhs_grenade_sthgr43_heerfrag_mag",
	"rhs_grenade_sthgr43_SSfrag_mag",
	"rhs_grenade_khattabka_vog17_mag",
	"rhs_grenade_khattabka_vog25_mag",
	"rhs_mag_an_m14_th3",
	"rhs_mag_m67",
	"rhs_grenade_sthgr24_mag",
	"rhs_grenade_sthgr24_heerfrag_mag",
	"rhs_grenade_sthgr24_SSfrag_mag",
	"rhs_grenade_sthgr24_x7bundle_mag",
	"rhs_charge_sb3kg_mag",
	"rhs_charge_tnt_x2_mag",
	"rhssaf_mag_brz_m88",
	"rhssaf_mag_br_m84",
	"rhssaf_mag_br_m75",
	"rhssaf_mag_brk_m79",
	"LIB_F1",
	"LIB_M39",
	"LIB_US_Mk_2",
	"LIB_MillsBomb",
	"LIB_No82",
	"LIB_Rg42",
	"LIB_Shg24",
	"LIB_Shg24x7",
	"LIB_Rpg6",
	"LIB_Pwm",
	"fow_e_mk2",
	"fow_e_no36mk1",
	"fow_e_no69",
	"fow_e_no73",
	"fow_e_no82",
	"fow_e_m24",
	"fow_e_m24K",
	"fow_e_m24_spli",
	"fow_e_m24K_spli",
	"fow_e_m24_at",
	"fow_e_type97",
	"fow_e_type99",
	"fow_e_type99_at",
	"fow_e_tnt_halfpound",
	"NORTH_M32MortarNade_mag",
	"NORTH_M43Grenade_mag",
	"NORTH_M32Grenade_mag",
	"NORTH_NOR_IMPROV_GRENADE",
	"NORTH_F1Grenade_mag",
	"NORTH_RG42Grenade_mag",
	"NORTH_RGD33Grenade_mag",
	"NORTH_Kasapanos2kg_mag",
	"NORTH_Kasapanos3kg_mag",
	"NORTH_Kasapanos4kg_mag",
	"NORTH_KasapanosImpr3kg_mag",
	"NORTH_KasapanosImpr6kg_mag"
];
